[project]
name = "pitwall"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anyio>=4.9.0",
    "orjson>=3.11.1",
    "pysignalr>=1.3.0",
    "requests>=2.32.4",
]

[dependency-groups]
dev = [
    "ruff>=0.12.7",
    "ty>=0.0.1a16",
]

